FileVersion = 2

Name = "mainnet1"

[[Metadata]]
Key = "network"
Value = "mainnet"

[API]
  [API.GRPC]
    Hosts = [
      "tls://vega-mainnet-data-grpc.commodum.io:443",
      "vega-grpc.mainnet.lovali.xyz:3007",
      "vega-data.bharvest.io:3007",
      "vega-data.nodes.guru:3007",
      "tls://grpc.velvet.tm.p2p.org:443",
      "vega-data-mainnet.rockrpc.net:3007",
      "vega.greenfield.xyz:3007",
      "tls://grpc.vega.xprv.io:443",
      "vega.mainnet.stakingcabin.com:3007",
      "vega-mainnet.anyvalid.com:3007",
      "grpcvega.gpvalidator.com:3007",
      "datanode.vega.pathrocknetwork.org:3007",
      "tls://vega-grpc.aurora-edge.com:443",
      "darling.network:3007"
    ]
    Retries = 5
  [API.REST]
    Hosts = [
      "https://vega-mainnet-data.commodum.io",
      "https://vega-query.mainnet.lovali.xyz",
      "https://vega-data.bharvest.io",
      "https://vega-data.nodes.guru:3008",
      "https://rest.velvet.tm.p2p.org",
      "https://vega-data-mainnet.rockrpc.net",
      "https://vega.greenfield.xyz",
      "https://vega.xprv.io/datanode",
      "https://vega.mainnet.stakingcabin.com",
      "https://vega-mainnet.anyvalid.com",
      "http://graphqlvega.gpvalidator.com:3008",
      "https://datanode.vega.pathrocknetwork.org",
      "https://vega.aurora-edge.com",
      "https://darling.network"
    ]
  [API.GraphQL]
    Hosts = [
      "https://vega-mainnet-data.commodum.io/graphql",
      "https://vega-query.mainnet.lovali.xyz/graphql",
      "https://vega-data.bharvest.io/graphql",
      "https://vega-data.nodes.guru:3008/graphql",
      "https://gql.velvet.tm.p2p.org/graphql",
      "https://vega-data-mainnet.rockrpc.net/graphql",
      "https://vega.greenfield.xyz/graphql",
      "https://vega.xprv.io/datanode/query",
      "https://vega.mainnet.stakingcabin.com/query",
      "https://vega-mainnet.anyvalid.com/graphql",
      "http://graphqlvega.gpvalidator.com:3008/graphql",
      "https://datanode.vega.pathrocknetwork.org/graphql",
      "https://vega.aurora-edge.com/graphql",
      "https://darling.network/graphql"
    ]

[Apps]
Console = ""
Governance = "https://governance.vega.xyz/"
Explorer = "https://explorer.vega.xyz/"
